<?php
/**
 * Plugin Name: Test Plugin Public Content Export Without Errors
 * Plugin URI: https://github.com/WordPress/plugin-check
 * Description: Test plugin that handles post content export safely with access-control guards.
 * Author: WordPress Performance Team
 * Author URI: https://make.wordpress.org/performance/
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * Text Domain: test-plugin-public-content-export-without-errors
 *
 * @package test-plugin-public-content-export-without-errors
 */

// Safe: file_put_contents with non-post-content data.
function test_safe_export() {
	$data = 'static page content generated by the plugin';
	file_put_contents( '/tmp/static-page.html', $data );
}

// Safe: file write with post_password_required guard.
function test_guarded_with_password_check() {
	$post = get_post( 42 );
	if ( post_password_required( $post ) ) {
		return;
	}
	file_put_contents( '/tmp/safe-export.html', $post->post_content );
}

// Safe: file write with current_user_can guard.
function test_guarded_with_cap_check() {
	$post = get_post( 42 );
	if ( ! current_user_can( 'read_post', $post->ID ) ) {
		return;
	}
	file_put_contents( '/tmp/member-export.html', $post->post_content );
}

// Safe: file write with is_post_type_viewable guard.
function test_guarded_with_viewable_check() {
	$post = get_post( 42 );
	if ( ! is_post_type_viewable( $post->post_type ) ) {
		return;
	}
	file_put_contents( '/tmp/public-export.html', get_the_content( null, false, $post ) );
}

// Safe: file write with is_user_logged_in guard.
function test_guarded_with_login_check() {
	if ( ! is_user_logged_in() ) {
		return;
	}
	file_put_contents( '/tmp/logged-in-export.html', get_the_content() );
}

// Safe: the_content() used standalone, not passed to file write.
function test_standalone_content() {
	the_content();
}

// Safe: fwrite with non-post-content property.
function test_non_content_property() {
	$post  = get_post( 42 );
	$fp    = fopen( '/tmp/title.txt', 'w' );
	fwrite( $fp, $post->post_title );
	fclose( $fp );
}

// Safe: get_post_field with non-post_content field.
function test_non_content_field() {
	$fp = fopen( '/tmp/field.txt', 'w' );
	fwrite( $fp, get_post_field( 'post_title', 42 ) );
	fclose( $fp );
}
