name: Spell Check

on: [pull_request]

jobs:
  spell-checker:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Search for misspellings
        uses: crate-ci/typos@v1.47.2
